hackforla/lucky-parking

team_members.txt
Adding a file where every team member can add their name to make sure they are able to pull request
=> [Set-up] add team members file

README.md, requirements.txt
Pin dependencies to `requirements.txt` and update installation instructions in `README.md`
=> Update README and requirements.txt

Lucky Parking Web App/client/src/components/app/Map.js, Lucky Parking Web App/server/controllers.js
Following changes have been made: 
1.  The map now refreshes and updates bikes when it moves and zooms in.
2. Changed the query to get more data for a bigger radius of bikes shown on the map.
=> Fixes for issue #145

js/package-lock.json
This should fix the dot-prop audit risk
=> fixed audit risk

js/client/src/components/app/Geosearch.js, js/client/src/components/app/map/Map.js, js/client/src/components/app/map/MapLayers.js, js/client/src/sass/components/_geosearch.scss, js/client/src/sass/components/_mainMap.scss, js/server/controllers.js
*Fix some of the styling issues with the search bar
* Changed the query to pick the test database
* Changed the map style to dark 
* Changed the bicycle markers to dots.
=> Fix mapstyles & Db for Test

js/client/src/components/app/map/MapLayers.js
*removed import line from maplayer.js
=> removed import line

js/client/src/components/app/map/Map.js, js/client/src/components/app/map/MapLayers.js
Easy to change colors, zoom transitions, etc. 
closes #162
=> heat map layer | transitions relative to zoom

js/client/src/components/app/map/Map.js
merged code had overlapping statements. Failed to deploy. Should be fixed. https://github.com/hackforla/lucky-parking/issues/162
=> Fix merge error

js/client/src/components/app/map/Map.js
Resolves #274, the first 2 action items and elected not to do the third.
=> restrict panning and search to area where we have data

js/client/src/components/app/Graph.js
=> bar graphs, formatting, sort descending, filter out zeros

js/client/src/components/app/map/Map.js, js/client/src/components/app/map/MapLayers.js, js/server/controllers.js
=> Zip code hover

js/client/src/components/app/map/Map.js
=> Deselect zip area when subsequently clicked

server/app.js, server/controllers/controllers.js, server/middleware/errors.middleware.js, server/middleware/httpRequests.middleware.js, server/package-lock.json, server/package.json
- Add morgan as the middleware for handling http requests logging
- Changed directory names for middleware to be more specific
=> Update middleware for http requests

js/client/src/components/app/map/Map.js
Removes freeahand to revert the draw tool to base functionality
=> Simplify polygon draw

.github/workflows/Continuous_Deployment_Dev_Client.yml
=> Add new gha

Makefile, src/data/get_zipcodes.py, src/data/upload_neighborhood.py, src/data/upload_zip.py
Script for downloading zip data, and script for uploading zip and neighborhood data.
Updated make file for the newly added files.
=> Add scripts for zip and neighborhood

server/.dockerignore, server/Dockerfile, server/docker-compose.yml
Adds Dockerfile for node and adds node service under docker-compose
=> Dockerize node

server/controllers/controllers.js, server/docker-compose.yml
Adds live reload when developing using docker
=> Add live reload

.gitignore, server/.gitignore, server/Dockerfile, server/docker-compose.dev.yml, server/docker-compose.yml
- Updated gitignore
- Updated docker to have prod file and dev override file
=> Update docker and gitignore

server/docker-compose.dev.yml, server/docker-compose.prod.yml, server/docker-compose.yml
- Simplify docker-compose.dev so it does not repeat properties from the base file
- Add docker-compose.prod for staging and prod environment
=> Add docker-compose file for prod

server/deploy.sh
- Modify dev aws instance to run node on docker instead of pm2
=> Add docker to dev ci/cd

Makefile, src/data/make_dataset.py, src/data/make_serial_data.py
Fixed broken columns and serial data generation
=> Fixed serial data generation and orig make data

src/data/make_dataset.py, src/data/make_serial_data.py
=> Formatting

requirements.txt, src/data/make_serial_data.py
Removed all symbols from datetime.
=> Updated serial data code with new date time format

notebooks/rough_regulation_extract.ipynb
Added some rough code to extract parking regulations.
=> Added regulation extraction notebook

libs/ui/src/assets/fonts/fonts.css, libs/ui/src/components/button/button.stories.tsx, libs/ui/src/components/button/button.tsx, libs/ui/src/components/button/index.ts, libs/ui/src/styles.css, libs/ui/tailwind.config.js, libs/ui/tsconfig.json
This pull request creates the button component and introduces small configuration changes to the UI library.
Resolves #439 
- I previewed the component in Storybook and used the controls to simulate the different props that the component may use.
=> Build button component

package.json, packages/ui/src/components/button/button.tsx, packages/ui/src/components/search-input/index.ts, packages/ui/src/components/search-input/search-input.tsx, packages/ui/src/design-system.preset.ts, packages/ui/tailwind.config.js, packages/website/src/features/area-search/area-search.tsx, packages/website/src/features/area-search/index.ts, packages/website/src/pages/main-page/main-page.tsx, packages/website/src/widgets/action-box/index.ts, packages/website/src/widgets/action-box/ui/action-box-section/action-box-section.tsx, packages/website/src/widgets/action-box/ui/action-box-section/index.ts, packages/website/src/widgets/action-box/ui/action-box.tsx, packages/website/src/widgets/action-box/ui/compare-section/compare-mode-button.tsx, packages/website/src/widgets/action-box/ui/compare-section/compare-section.tsx, packages/website/src/widgets/action-box/ui/compare-section/index.ts, packages/website/src/widgets/action-box/ui/single-search-section/draw-boundary-button.tsx, packages/website/src/widgets/action-box/ui/single-search-section/index.ts, packages/website/src/widgets/action-box/ui/single-search-section/single-search-section.tsx, packages/website/src/widgets/header/header.tsx, pnpm-lock.yaml
=> Build action box

.github/ISSUE_TEMPLATE/team-offboarding.yaml, .github/ISSUE_TEMPLATE/team-onboarding.yaml
This PR creates onboarding and offboarding issue templates to assist in the management of our team.
Resolves #476 
Resolves #477
=> Create onboarding and offboarding issue templates

packages/website/README.md
=> Update website README

pnpm-lock.yaml
=> Update package lock file

jest.config.ts, package.json, packages/ui/src/components/button/button.tsx, packages/ui/src/components/modal/index.ts, packages/ui/src/components/modal/modal.stories.tsx, packages/ui/src/components/modal/modal.test.tsx, packages/ui/src/components/modal/modal.tsx, pnpm-lock.yaml
Implement Modal Feature with [Radix Dialog API](https://www.radix-ui.com/docs/primitives/components/dialog)
Resolves #529 
```
PASS  packages/website/src/widgets/header/header.test.tsx
PASS  packages/ui/src/components/modal/modal.test.tsx
Test Suites: 2 passed, 2 total
Tests:       11 passed, 11 total
Time:        15.76 s
Ran all test suites.
✨  Done in 17.03s.
```
ui/src/components/modal                                  |   56.25 |      100 |      50 |   56.25 |                   
modal.stories.tsx                                       |       0 | …
=> Basic Modal Feature

package.json, packages/ui/src/components/button/button.tsx, packages/ui/src/components/modal/index.ts, packages/ui/src/components/modal/modal.stories.tsx, packages/ui/src/components/modal/modal.test.tsx, packages/ui/src/components/modal/modal.tsx, packages/website/src/widgets/header/header.test.tsx, packages/website/src/widgets/header/header.tsx, packages/website/src/widgets/header/how-it-works-button.test.tsx, packages/website/src/widgets/header/how-it-works-button.tsx, pnpm-lock.yaml
1. For Modal. Developer can add custom title and description
2. HowItWorksButton was implemented with above feature
Resolves #535 
- ran all test suites 
```
PASS  packages/website/src/widgets/header/header.test.tsx (9.836 s)
PASS  packages/website/src/widgets/header/how-it-works-button.test.tsx (10.162 s)
PASS  packages/ui/src/components/modal/modal.test.tsx (10.463 s)
Test Suites: 3 passed, 3 total
Tests:       25 passed, 25 total
Time:        22.673 s
Ran all test suites.
✨  Done in 24.14s.
```
ui/src/components/modal …
=> Implement Dialog for How it Works Button

jest.setup.ts, package.json, packages/ui/src/components/pick-list/index.ts, packages/ui/src/components/pick-list/pick-list-test-data.ts, packages/ui/src/components/pick-list/pick-list.stories.tsx, packages/ui/src/components/pick-list/pick-list.test.tsx, packages/ui/src/components/pick-list/pick-list.tsx, pnpm-lock.yaml
PickList's width by default fills to parent container and allows developers to insert custom width if needed.
Resolves #522 
```
PASS  packages/website/src/widgets/header/header.test.tsx
PASS  packages/ui/src/components/modal/modal.test.tsx
PASS  packages/website/src/widgets/header/how-it-works-button.test.tsx
PASS  packages/ui/src/components/pick-list/pick-list.test.tsx (5.029 s)
Test Suites: 4 passed, 4 total
Tests:       29 passed, 29 total
Time:        15.214 s
```
.../pick-list |   47.82 |      100 |   28.57 |      50 | …
=> Implement PickList Component

packages/ui/src/components/input/index.ts, packages/ui/src/components/input/input.stories.tsx, packages/ui/src/components/input/input.test.tsx, packages/ui/src/components/input/input.tsx, packages/ui/src/components/pick-list/pick-list.tsx, packages/website/src/pages/parking-insights-page.tsx, packages/website/src/widgets/radius-tool/index.ts, packages/website/src/widgets/radius-tool/radius-tool.test.tsx, packages/website/src/widgets/radius-tool/radius-tool.tsx, packages/website/src/widgets/radius-tool/utils/formatDecimals.ts, packages/website/src/widgets/radius-tool/utils/unit-convertor.ts
- Input Component Created
- Radius Tool Implemented
- Unit Convertor also implemented with Strategy pattern
Missing the point and radius circle
Resolves #538 
```
PASS  packages/website/src/widgets/header/how-it-works-button.test.tsx (6.141 s)
PASS  packages/ui/src/components/input/input.test.tsx
PASS  packages/website/src/widgets/header/header.test.tsx
PASS  packages/website/src/widgets/radius-box/radius-tool.test.tsx (6.293 s)
Test Suites: 6 passed, 6 total
Tests:       38 passed, 38 total
Time:        19.183 s
```
---------------------------|---------|----------|---------|---------|-------------------
ui/src/components/input …
=> Radius Tool with Unit Convertor

packages/ui/src/components/stepper/index.ts, packages/ui/src/components/stepper/stepper-circle.tsx, packages/ui/src/components/stepper/stepper-container.tsx, packages/ui/src/components/stepper/stepper-item.tsx, packages/ui/src/components/stepper/stepper-line.tsx, packages/ui/src/components/stepper/stepper.stories.tsx, packages/ui/src/components/stepper/stepper.test.tsx
Implement Stepper Components 
Resolves #521 
```
PASS  packages/ui/src/components/modal/modal.test.tsx
PASS  packages/website/src/features/instructions/how-it-works-button.test.tsx
FAIL  packages/website/src/widgets/header/header.test.tsx
Test Suites: 1 failed, 4 passed, 5 total
Tests:       32 passed, 32 total
Time:        19.803 s
```
ui/src/components/stepper                     |   66.66 |    77.27 |    62.5 |   70.37 |                   
index.ts                                     |       0 |      100 |       0 |       0 | 1-2 …
=> feat(ui): Implement stepper component

.github/ISSUE_TEMPLATE/defect-report.yaml, .github/ISSUE_TEMPLATE/epic.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/ISSUE_TEMPLATE/task.yaml, .github/ISSUE_TEMPLATE/team-onboarding.yaml
=> Update issue templates

packages/api-express/docs/specs-v1.yaml
This PR creates a YAML file that defines the API specifications.
Resolves #551 
N/A
=> Define API specifications

.dockerignore, Dockerfile, README.md, docker-compose.yaml, nx.json, package.json, packages/api-express/package.json, packages/api-express/tsconfig.json, packages/ui/package.json, packages/website/package.json, pnpm-lock.yaml, scripts/prepare.js
This PR dockerizes the project, including some configuration changes that support this operation.
Resolves #554 
- Follow instructions in README.
=> Dockerize project

packages/api-express/src/database/db.ts, packages/api-express/src/database/index.ts, packages/api-express/src/services/citations.ts
Implement database query with for citation service
Resolves #557 
N/A
=> feat(api): implement post citation service query

packages/website/src/features/citation/ui/citation-data-category-selection.test.tsx, packages/website/src/features/citation/ui/citation-date-presets-selection.test.tsx, packages/website/src/features/citation/ui/citation-date-presets-selection.tsx
Adds tests files for Citation-Data-Category-Selection and Citation-Date-Presets-Selection
- Tests for component rendering
- Tests for user selection of options using provided constants
Resolves #573 #576 
=> Testing citation data/date selection

packages/website/src/main.tsx
=> Ignore main file in testing

packages/website/src/pages/page.test.tsx, packages/website/src/shared/lib/utilities/testing/index.ts, packages/website/src/shared/lib/utilities/testing/mock-component.tsx
This PR tests the `Page` component and introduces the `MockComponent` component that may be used for testing.
Resolves #584
=> Test page component

packages/website/src/shared/lib/utilities/string.test.ts
This PR provides complete testing of the string utility functions.
```
String Utilities
isSubstring
✓ handles without case-sensitivity (5 ms)
✓ handles with case-sensitivity (1 ms)
```
Resolves #587 
- Ran existing testing suites
- Write new tests
```
-----------------------------------------------|---------|----------|---------|---------|-----------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s     
-----------------------------------------------|---------|----------|---------|---------|-----------------------
src/shared/lib/utilities                      |   13.79 |     37.5 |   16.66 |      15 |                       
string.ts                                    |     100 |      100 |     100 |     100 | …
```
=> Test string utilities

packages/website/src/shared/lib/utilities/enum.test.ts, packages/website/src/shared/lib/utilities/enum.ts, packages/website/src/widgets/citation/ui/visualization/comparative-search-visualization-focused.tsx, packages/website/src/widgets/citation/ui/visualization/comparative-search-visualization.tsx, packages/website/src/widgets/citation/ui/visualization/single-search-visualization.tsx
This PR provides complete testing of the enum utility functions.
```
Enum Utilities
getNth
✓ gets the nth enum (2 ms)
✓ returns undefined for out-of-bounds nth
getFirst
✓ gets first enum
✓ returns undefined for empty enum
```
Resolves #586
- Ran existing testing suites
- Wrote new tests
```
-----------------------------------------------|---------|----------|---------|---------|-----------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s     
-----------------------------------------------|---------|----------|---------|---------|-----------------------
src/shared/lib/utilities                      |   24.13 |        0 |   33.33 |      15 |                       
enum.ts                                      |     100 | …
```
=> Test enum utilities

packages/website/src/features/geocoder/api/endpoints.test.tsx
Added endpoint testing file for available endpoints validating structure and url build for
- FORWARD_GEOCODING
Resolves #577 
- Ran testing suites
Copy of Test
```
PASS  src/features/geocoder/api/endpoints.test.tsx
Endpoint Testing
✓ should outline forward geocoding endpoint (2 ms)
✓ should correctly build a forward geocoding endpoint url with params (2 ms)
```
Copy of Coverage
-----------------------------------------------|---------|----------|---------|---------|-----------------------
File                                           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s     
-----------------------------------------------|---------|----------|---------|---------|-----------------------
src/features/geocoder/api                     |   66.66 |       25 |      50 | …
=> Test api endpoints

packages/website/src/features/geocoder/ui/region-types-selection.test.tsx
Tests region-types-selection.tsx
- should test that all region types are rendered
- should test that user can select region type
Resolves #582 
```
PASS  src/features/geocoder/ui/region-types-selection.test.tsx
Region Types Selection
✓ should render all available Region Types (76 ms)
✓ should allow user select specific region type (24 ms)
```
src/features/geocoder/ui                      |    8.57 |        0 |    7.14 |    9.09 | …
=> Test /region-types-selection

packages/ui/src/components/loader/index.ts, packages/ui/src/components/loader/loader.test.tsx, packages/ui/src/components/loader/loader.tsx, packages/website/src/features/citation/ui/citation-data-insights.tsx
1. Implemented a circular loader component
2. Wrapped citation-data-insights with a loader
Resolves #619
=> Added fallback loader for citation-data-insights

packages/ui/src/components/loader/loader.tsx
- Updated Loader component declaration with proptypes following `const App = ({ message }: AppProps) => <div>{message}</div>;
` format.
- Moved comments on props to interface
Resolves #633 
- Ran `ci:lint`, no more prop-types warnings.
=> Fixed lint prop-types warnings; moved comments
